#!/usr/bin/env python3
"""Fix LexSpec gold annotations for fix_batch_bcd_3.jsonl (47 items)."""

from __future__ import annotations

import copy
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "data/processed/curated_500/fix_batch_bcd_3.jsonl"
OUTPUT = ROOT / "data/processed/curated_500/fixed_batch_bcd_3.jsonl"

WITHOUT_CONSENT_RE = re.compile(
    r"\bwithout\s+(?:the\s+)?(?:prior\s+)?(?:written\s+)?(?:express\s+)?(?:approval|consent)\b",
    re.I,
)
NEGATION_RE = re.compile(
    r"\b(shall not|may not|must not|will not|neither\b|no party may|not be allowed|"
    r"shall not apply|undertakes not to|agrees that it will not|intent not to|"
    r"not to be renewed|not to renew|will not be|to not pay|fail to take)\b",
    re.I,
)
GOVERN_RE = re.compile(r"\b(shall be governed|is governed|governed by)\b", re.I)
TERM_PREDICATES = frozenset({
    "commence", "begin", "start", "end", "expire", "renew", "continue",
    "terminate", "become", "remain", "extend",
})

# Per curate_batch_3.py MANUAL + BCD-specific gold
MANUAL: dict[str, dict] = {
    "C-00245": {
        "action": {
            "object": "this Agreement or any of the rights or obligations contained herein",
        },
        "condition": {
            "text": "without the prior written consent of the other Party",
            "type": "exception",
        },
        "note": "C-00006 pattern: without-consent exception; nor→or object; sync conditional+negation",
    },
    "C-00248": {
        "subject": {"text": "Wade and Naked", "role": "obligor"},
        "action": {
            "object": (
                "All rights to the use of the names, trademarks, service marks, symbols, logos, "
                "domain names, trade secrets, confidential know-how, patents, copyrights, "
                "any pending applications with respect to any of the foregoing, and any other "
                "intellectual property and related proprietary rights"
            ),
        },
        "note": "passive agent from by-phrase; trim object to complete NP",
    },
    "C-00260": {
        "phenomena": {"is_definition": True},
        "condition": {
            "text": "except as otherwise provided in this Agreement",
            "type": "exception",
        },
        "note": "definition clause; exception carve-out; sync conditional from annotation",
    },
    "C-00262": {
        "condition": {"text": "", "type": "none"},
        "note": "without-consent inline on prohibition; passive shall-not-be-entitled",
    },
    "C-00263": {
        "action": {
            "object": (
                "5% (five percent) of the capital expenditure as agreed among the parties for "
                "the particular Smaaash Centre as sign-on fees or upfront advance, and "
                "5% (five percent) fee or commission of the revenue generated by such third "
                "party franchisees from the Smaash Centres on an annual basis"
            ),
        },
        "note": "complete receive object spanning both fee items",
    },
    "C-00269": {
        "action": {
            "object": (
                "Franchisor's interest in, or the validity of, any Franchisor Property, "
                "or any application for registration or trademark registration thereof "
                "or any rights of Franchisor therein"
            ),
        },
        "note": "trim object to complete prohibition scope",
    },
    "C-00285": {
        "subject": {"role": "other"},
        "action": {"object": ""},
        "note": "auto-renewal declarative; empty object not literal none",
    },
    "C-00299": {
        "condition": {"text": "", "type": "none"},
        "note": "manner notice/payment steps are procedural, not subordinate condition",
    },
    "C-00302": {
        "phenomena": {"conditional": False},
        "note": "necessary-for purpose clause is not a subordinate condition",
    },
    "C-00303": {
        "condition": {"text": "", "type": "none"},
        "note": "solely-in-connection scope modifier is inline, not trigger condition",
    },
    "C-00307": {
        "phenomena": {"conditional": False},
        "note": "no subordinate condition clause in text",
    },
    "C-00318": {
        "phenomena": {"conditional": False},
        "note": "will-not complement is prohibition frame, not advcl condition",
    },
    "C-00324": {
        "action": {
            "object": (
                "a non-exclusive, royalty-free, fully-paid, perpetual, sublicenseable "
                "(solely to Subsidiaries and suppliers for \"have-made\" purposes), worldwide "
                "license to use and exercise rights under the Honeywell Shared IP"
            ),
        },
        "note": "trim grant object to minimal complete NP",
    },
    "C-00325": {
        "action": {
            "object": (
                "a non-exclusive, royalty-free, fully-paid, non-sublicenseable, non-transferable, "
                "worldwide license to use and reproduce the Honeywell Content"
            ),
        },
        "note": "trim grant object; temporal+unless condition retained",
    },
    "C-00332": {
        "action": {
            "object": (
                "Investor at least sixty (60) days prior written notice and an opportunity "
                "to take over the prosecution of the patent application that would be abandoned"
            ),
        },
        "note": "trim give object to core notice+opportunity NP",
    },
    "C-00343": {
        "condition": {
            "text": "without the prior written consent of the other Party",
            "type": "exception",
        },
        "note": "C-00006 pattern: without-consent exception on prohibition",
    },
    "C-00355": {
        "condition": {
            "text": "without regard to conflicts of law provisions",
            "type": "exception",
        },
        "note": "govern clause parenthetical is exception condition",
    },
    "C-00359": {
        "condition": {"text": "", "type": "none"},
        "note": "without-consent inline on prohibition frame",
    },
    "C-00364": {
        "action": {
            "object": (
                "a worldwide, non-exclusive, limited, non-sublicenseable and non-assignable "
                "right and license to Exploit the PFHOF Works"
            ),
        },
        "condition": {"text": "", "type": "none"},
        "note": "subject-to is inline trigger modifier; trim grant object",
    },
    "C-00378": {
        "action": {
            "object": (
                "an exclusive, irrevocable, worldwide, sublicensable (including through multiple "
                "tiers), transferrable (without consent) royalty free license to any and all "
                "right, title and/or interest that it may have in or to an Invention"
            ),
        },
        "note": "trim grant object to complete license NP",
    },
    "C-00379": {
        "condition": {
            "text": "without CytoDyn's written consent",
            "type": "exception",
        },
        "note": "C-00006 pattern: without-consent exception on prohibition",
    },
    "C-00404": {
        "action": {
            "object": (
                "the exclusive owner of all right, title, and interest in and to all "
                "Paid-For Development (defined below), including all Intellectual Property Rights"
            ),
        },
        "note": "trim owner object to core NP",
    },
    "C-00416": {
        "action": {
            "object": (
                "whether the Bloom Systems in the Portfolio during such Power Performance "
                "Warranty Period have delivered to the Interconnection Point the Minimum kWh"
            ),
        },
        "note": "trim determine clausal-complement object",
    },
    "C-00424": {
        "condition": {
            "text": "as of the date of this agreement",
            "type": "temporal",
        },
        "note": "subject-to is inline; temporal as-of retained",
    },
    "C-00426": {
        "subject": {"role": "other"},
        "note": "commencement term clause is declarative",
    },
    "C-00427": {
        "subject": {"role": "other"},
        "action": {"object": ""},
        "note": "auto-renewal declarative; empty object",
    },
    "C-00431": {
        "phenomena": {"conditional": False},
        "note": "notwithstanding is override frame; manner notice is not condition",
    },
    "C-00433": {
        "phenomena": {"conditional": False},
        "note": "in-order-to purpose phrase is not subordinate condition",
    },
}


def has_negation(text: str) -> bool:
    return bool(NEGATION_RE.search(text))


def sync_conditional(phen: dict, triplet: dict) -> dict:
    phen = dict(phen)
    has_cond = bool((triplet.get("condition") or {}).get("text", "").strip())
    if has_cond:
        phen["conditional"] = True
    elif "conditional" not in phen or phen.get("conditional") is not False:
        # only clear if not explicitly set false in manual
        if not has_cond:
            phen["conditional"] = phen.get("conditional", False)
    return phen


def apply_manual(triplet: dict, phen: dict, patch: dict) -> tuple[dict, dict]:
    t = copy.deepcopy(triplet)
    p = copy.deepcopy(phen)
    for key, val in patch.items():
        if key == "note":
            continue
        if key == "phenomena":
            p.update(val)
        elif key in ("subject", "action", "condition"):
            t[key] = {**t.get(key, {}), **val}
        else:
            t[key] = copy.deepcopy(val)
    return t, p


def auto_fix(triplet: dict, text: str) -> dict:
    t = copy.deepcopy(triplet)
    obj = (t.get("action") or {}).get("object") or ""
    if obj.lower() == "none":
        t["action"]["object"] = ""

    cond = t.get("condition") or {}
    ctext = (cond.get("text") or "").strip()
    if ctext.lower() == "none":
        t["condition"] = {"text": "", "type": "none"}
        ctext = ""
    if not ctext:
        t["condition"] = {"text": "", "type": "none"}
    elif cond.get("type") == "none":
        low = ctext.lower()
        if any(m in low for m in ("unless", "except", "notwithstanding", "regardless")):
            t["condition"]["type"] = "exception"
        elif any(
            m in low
            for m in (
                "when ", "upon ", "after ", "before ", "during ", "within ",
                "following ", "on or before", "commencing", "as of ",
                "in january", "for a period", "for one (", "prior to",
            )
        ):
            t["condition"]["type"] = "temporal"
        elif any(
            m in low
            for m in ("if ", "in the event", "provided that", "subject to", "so long as", "in case")
        ):
            t["condition"]["type"] = "trigger"

    pred = (t.get("action") or {}).get("predicate", "")
    subj = (t.get("subject") or {}).get("text", "")
    if pred in TERM_PREDICATES and re.search(
        r"\b(term|agreement|license|this agreement)\b", subj, re.I
    ):
        t["subject"] = {**t["subject"], "role": "other"}

    if GOVERN_RE.search(text):
        m = re.search(r"\b(?:the )?laws of [^.;,\n(]+", text, re.I)
        if m:
            laws = m.group(0).strip()
            obj_agr = "This Agreement" if "this agreement" in text.lower() else "the Agreement"
            t = {
                **t,
                "subject": {"text": laws, "role": "other"},
                "action": {"predicate": "govern", "object": obj_agr},
            }
            if re.search(r"constru", text, re.I):
                t["action"]["predicate"] = "construe"
            exc = re.search(r"(without regard to[^.;,\n)]+)", text, re.I)
            t["condition"] = (
                {"text": exc.group(1).strip(), "type": "exception"}
                if exc
                else {"text": "", "type": "none"}
            )

    return t


def fix_record(rec: dict) -> dict:
    cid = rec["clause_id"]
    text = rec["text"]
    triplet = copy.deepcopy(rec["triplet"])
    phen = copy.deepcopy(rec["phenomena"])
    notes: list[str] = []

    triplet = auto_fix(triplet, text)

    if cid in MANUAL:
        patch = MANUAL[cid]
        triplet, phen = apply_manual(triplet, phen, patch)
        if patch.get("note"):
            notes.append(patch["note"])

    if "negation_not_tagged" in rec.get("issues", []):
        if has_negation(text):
            phen["negation"] = True
            notes.append("sync negation flag with deontic negation in text")

    if "cond_annot_no_flag" in rec.get("issues", []):
        phen = sync_conditional(phen, triplet)
        if phen.get("conditional"):
            notes.append("sync conditional=true with annotated condition")

    if "cond_flag_no_annot" in rec.get("issues", []):
        has_cond = bool((triplet.get("condition") or {}).get("text", "").strip())
        if not has_cond and phen.get("conditional"):
            phen["conditional"] = False
            notes.append("sync conditional=false; no subordinate condition in triplet")

    if "missing_object" in rec.get("issues", []):
        # intransitive shall-not-apply: subject carries theme, empty object is correct
        if (triplet.get("action") or {}).get("predicate") == "apply":
            triplet["action"]["object"] = ""
            notes.append("intransitive apply: empty object correct for limitation carve-out")

    # final sync
    phen = sync_conditional(phen, triplet)
    if has_negation(text):
        phen["negation"] = True

    # passive sync for obvious passive main clauses
    if re.search(r"\b(?:shall|may|will) be \w+ed\b", text, re.I):
        phen["passive"] = True
    if re.search(r"\bwill not be allowed\b", text, re.I):
        phen["passive"] = True

    if re.search(r'\bshall mean\b', text, re.I) or (
        text.strip().startswith('"') and "mean" in text.lower()
    ):
        phen["is_definition"] = True

    if re.search(r"\bwho\b|\bwhich\b|\bthat would\b", text, re.I):
        phen["relative_clause"] = True

    return {
        "clause_id": cid,
        "triplet": triplet,
        "phenomena": phen,
        "fix_notes": "; ".join(dict.fromkeys(notes)) if notes else "validated; no triplet change needed",
    }


def main() -> None:
    records = [
        json.loads(line)
        for line in INPUT.read_text().splitlines()
        if line.strip()
    ]
    assert len(records) == 47, f"expected 47 items, got {len(records)}"

    out = [fix_record(r) for r in records]

    with OUTPUT.open("w") as f:
        for row in out:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    changed = sum(
        1 for orig, fixed in zip(records, out)
        if orig["triplet"] != fixed["triplet"] or orig["phenomena"] != fixed["phenomena"]
    )
    print(json.dumps({
        "input": str(INPUT),
        "output": str(OUTPUT),
        "count": len(out),
        "changed": changed,
        "clause_ids": [r["clause_id"] for r in out],
    }, indent=2))


if __name__ == "__main__":
    main()
